# Generated by Django 5.1.7 on 2025-03-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_relatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(upload_to='produtos/'),
        ),
    ]
