# Generated by Django 5.1.7 on 2025-03-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_alter_empresa_quant_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Tipos',
        ),
    ]
